openapi: 3.0.2
info:
  title: Order interface
  version: 1.0.0
servers:
  - url: /orders/api
  - url: 'https://order.test.sunesis.si/orders/api'
  - url: 'https://order.sunesis.si/orders/api'
paths:
  /products/{company}:
    get:
      tags:
        - products
      summary: Retrieve products
      description: Returns all products
      operationId: getProducts
      parameters:
        - name: company
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  title: Product
                  type: object
                  properties:
                    company:
                      type: string
                    name:
                      type: string
                    price:
                      type: number
